[package]
name = "monero_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.2"
app_monero = { path = "../../../apps/monero" }
common_rust_c = {path = "../common"}
ur-registry = { workspace = true }
keystore = { workspace = true }
app_utils = { workspace = true }
cstr_core = { workspace = true }
hex = { workspace = true }

[features]
debug-memory = []