[package]
name = "monero_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app_monero = { path = "../../../apps/monero" }

[features]
debug-memory = []