
#ifdef NORMAL_PARAM_BEGIN
#undef NORMAL_PARAM_BEGIN
#endif

#ifdef NORMAL_PARAM_ITEM
#undef NORMAL_PARAM_ITEM
#endif

#ifdef NORMAL_PARAM_END
#undef NORMAL_PARAM_END
#endif

#ifdef PROTECTED_PARAM_BEGIN
#undef PROTECTED_PARAM_BEGIN
#endif

#ifdef PROTECTED_PARAM_ITEM
#undef PROTECTED_PARAM_ITEM
#endif

#ifdef PROTECTED_PARAM_END
#undef PROTECTED_PARAM_END
#endif

