//! Firmware version stamped into every signed PCZT response via
//! `global.proprietary["keystone:fw_version"]`.
//!
//! Wallets read this stamp to decide whether the device meets their
//! minimum version requirements. The firmware itself does not enforce
//! any minimum, it just reports its own version.
//!
//! Version encoding is three raw bytes `[major, minor, build]`, matching the
//! `SOFTWARE_VERSION_MAJOR / MINOR / BUILD` triple in `src/config/version.h`.
//!
//! `KEYSTONE_FW_VERSION` is generated at compile time by `build.rs` from
//! `src/config/version.h` — no manual sync needed.

use crate::errors::ZcashError;
use alloc::string::ToString;

// Generated by build.rs from src/config/version.h.
include!(concat!(env!("OUT_DIR"), "/version_generated.rs"));

/// A `[major, minor, build]` firmware version triple.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Version(pub u8, pub u8, pub u8);

impl Version {
    /// Raw 3-byte encoding used in `global.proprietary` values.
    pub fn encode(&self) -> [u8; 3] {
        [self.0, self.1, self.2]
    }

    /// Parses the 3-byte encoding.
    pub fn parse(bytes: &[u8]) -> Result<Self, ZcashError> {
        if bytes.len() != 3 {
            return Err(ZcashError::InvalidPczt(
                "firmware version must be 3 bytes [major, minor, build]".to_string(),
            ));
        }
        Ok(Version(bytes[0], bytes[1], bytes[2]))
    }

    pub fn major(&self) -> u8 {
        self.0
    }
    pub fn minor(&self) -> u8 {
        self.1
    }
    pub fn build(&self) -> u8 {
        self.2
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    extern crate std;

    #[test]
    fn encode_round_trip() {
        let v = KEYSTONE_FW_VERSION;
        let encoded = v.encode();
        assert_eq!(encoded, [v.major(), v.minor(), v.build()]);
        assert_eq!(Version::parse(&encoded).unwrap(), v);
    }

    #[test]
    fn parse_rejects_wrong_length() {
        assert!(Version::parse(&[]).is_err());
        assert!(Version::parse(&[1, 2]).is_err());
        assert!(Version::parse(&[1, 2, 3, 4]).is_err());
    }

    #[test]
    fn ordering_is_lexicographic() {
        assert!(Version(12, 4, 0) < Version(12, 4, 1));
        assert!(Version(12, 4, 0) < Version(12, 5, 0));
        assert!(Version(12, 4, 0) < Version(13, 0, 0));
        assert!(Version(12, 4, 0) == Version(12, 4, 0));
    }
}
