[package]
name = "zcash_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { path = "../../../keystore", default-features = false }
app_zcash = {path = "../../../apps/zcash"}
third_party = { path = "../../../third_party" }
app_utils = { path = "../../../apps/utils" }
rust_tools = {path="../../../tools"}
common_rust_c = {path = "../common"}

[features]
debug-memory = []