set(LIB_NAME librust_c.a)
set(RUST_C_DIR ${RUST_DIR}/rust_c)

if(COMPILE_SIMULATOR)
    if(BTC_ONLY)
        set(CBINDGEN_CONFIG_PATH ${RUST_C_DIR}/cbindgens/simulator/btc_only.toml)
    else()
        set(CBINDGEN_CONFIG_PATH ${RUST_C_DIR}/cbindgens/simulator/multi_coin.toml)
    endif()
else()
    if(BTC_ONLY)
        set(CBINDGEN_CONFIG_PATH ${RUST_C_DIR}/cbindgens/release/btc_only.toml)
    else()
        set(CBINDGEN_CONFIG_PATH ${RUST_C_DIR}/cbindgens/release/multi_coin.toml)
    endif()
endif()
set(CBINDGEN_FLAG ${RUST_C_DIR} --config ${CBINDGEN_CONFIG_PATH} --output ${TARGET_PATH}/librust_c.h --lang c)
set(CARGO_TOML_PATH ${RUST_C_DIR}/Cargo.toml)