include_guard = "_LIBRUST_C_H"

after_includes = "#define BUILD_MULTI_COINS\n#define SIMPLERESPONSE_C_CHAR_MAX_LEN 2048\n#define ADDRESS_MAX_LEN 128\n#define PATH_ITEM_MAX_LEN 32"

[defines]
"feature = multi-coins" = "BUILD_MULTI_COINS"

[parse]
parse_deps = true
include = [
    "rust_c",
    "common_rust_c",
    "bitcoin_rust_c",
    "ethereum_rust_c",
    "solana_rust_c",
    "near_rust_c",
    "aptos_rust_c",
    "cosmos_rust_c",
    "cardano_rust_c",
    "sui_rust_c",
    "ton_rust_c",
    "zcash_rust_c",
    "tron_rust_c",
    "xrp_rust_c",
    "arweave_rust_c",
    "stellar_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "multi_coins_wallet_rust_c",
]
extra_bindings = [
    "common_rust_c",
    "bitcoin_rust_c",
    "ethereum_rust_c",
    "solana_rust_c",
    "near_rust_c",
    "aptos_rust_c",
    "cosmos_rust_c",
    "cardano_rust_c",
    "sui_rust_c",
    "ton_rust_c",
    "zcash_rust_c",
    "tron_rust_c",
    "xrp_rust_c",
    "arweave_rust_c",
    "stellar_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "multi_coins_wallet_rust_c",
]

[parse.expand]
crates = [
    "rust_c",
    "common_rust_c",
    "bitcoin_rust_c",
    "ethereum_rust_c",
    "solana_rust_c",
    "ton_rust_c",
    "near_rust_c",
    "aptos_rust_c",
    "cosmos_rust_c",
    "cardano_rust_c",
    "sui_rust_c",
    "zcash_rust_c",
    "tron_rust_c",
    "xrp_rust_c",
    "arweave_rust_c",
    "stellar_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "multi_coins_wallet_rust_c",
]
default_features = true
