[package]
name = "multi_coins_wallet_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_wallets = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
app_arweave = { workspace = true }
app_monero = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
ur-registry = { workspace = true }
hex = { workspace = true }
bitcoin = { workspace = true }
common_rust_c = { path = "../../../common" }
ed25519-bip32-core = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["multi-coins"]
multi-coins = []
btc-only = []