[package]
name = "firmware-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fmc"
test = false
bench = false
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
thiserror = "1"
bytes="1.4"
quicklz="0.3.1"
serde= {version="1.0.*", features=["derive"]}
secp256k1={version="0.27.0", features=["bitcoin-hashes-std"]}
tokio = { version = "1", features = ["full"] }
hex = "0.4.3"
byteorder = "1.5.0"
