#include "drv_ili9806.h"
#include "stdio.h"
#include "mhscpu.h"
#include "cmsis_os.h"
//#include "test_image_480_800.h"
//#include "test_image.h"
#include "user_memory.h"
#include "log_print.h"
#include "user_delay.h"
#include "user_utils.h"
#include "drv_parallel8080.h"

uint8_t g_c7param = 0x44;

static void Ili9806WriteCmd(uint8_t cmd);
static void Ili9806WriteData(uint8_t data);
static void Ili9806SetWindow(uint16_t xStart, uint16_t yStart, uint16_t xEnd, uint16_t yEnd);
static void Ili9806InitSequence(void);


static void Ili9806WriteCmd(uint8_t cmd)
{
    PARALLEL_8080_CS_CLR;
    LCDI_Write(LCD, LCDI_CMD, cmd);
    PARALLEL_8080_CS_SET;
}

static void Ili9806WriteData(uint8_t data)
{
    PARALLEL_8080_CS_CLR;
    LCDI_Write(LCD, LCDI_DAT, data);
    PARALLEL_8080_CS_SET;
}


void Ili9806Init(void)
{
    Parallel8080Init();
    UserDelay(50);
    Parallel8080Reset();   //初始化之前复位
    Ili9806InitSequence();
}


static void Ili9806SetWindow(uint16_t xStart, uint16_t yStart, uint16_t xEnd, uint16_t yEnd)
{
    Ili9806WriteCmd(0x2A);
    Ili9806WriteData(xStart >> 8);
    Ili9806WriteData(xStart);
    Ili9806WriteData(xEnd >> 8);
    Ili9806WriteData(xEnd);

    Ili9806WriteCmd(0x2B);
    Ili9806WriteData(yStart >> 8);
    Ili9806WriteData(yStart);
    Ili9806WriteData(yEnd >> 8);
    Ili9806WriteData(yEnd);

    Ili9806WriteCmd(0x2C);
}


bool Ili9806Busy(void)
{
    return Parallel8080Busy();
}


void Ili9806Clear(uint16_t color)
{
    uint32_t i;
    uint8_t *ramImg;
    uint32_t startTick, endTick;

    while (Parallel8080Busy());
    ramImg = EXT_MALLOC(ILI9806_HEIGHT * ILI9806_WIDTH * 2);
    if (ramImg == NULL) {
        printf("clear malloc err\r\n");
        return;
    }
    for (i = 0; i < ILI9806_WIDTH * ILI9806_HEIGHT ; i++) {
        ramImg[i * 2] = color >> 8;
        ramImg[i * 2 + 1] = color;
    }
    Ili9806SetWindow(0, 0, ILI9806_WIDTH - 1, ILI9806_HEIGHT - 1);
    startTick = osKernelGetTickCount();
    Parallel8080SendDmaData(ramImg, ILI9806_HEIGHT * ILI9806_WIDTH * 2);
    while (Parallel8080Busy());
    endTick = osKernelGetTickCount();
    EXT_FREE(ramImg);
    printf("frame tick=%d\r\n", endTick - startTick);
}


void Ili9806Draw(uint16_t xStart, uint16_t yStart, uint16_t xEnd, uint16_t yEnd, uint16_t *colors)
{
    uint32_t bytes;
    Ili9806SetWindow(xStart, yStart, xEnd, yEnd);
    bytes = (yEnd - yStart + 1) * (xEnd - xStart + 1) * 2;
    Parallel8080SendDmaData((uint8_t *)colors, bytes);
}


static void Ili9806InitSequence(void)
{
    Ili9806WriteCmd(0xFF); // EXTC Command Set enable register
    Ili9806WriteData(0xFF);
    Ili9806WriteData(0x98);
    Ili9806WriteData(0x06);

    Ili9806WriteCmd(0xBC); // GIP 1
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x0F);
    Ili9806WriteData(0x61);
    Ili9806WriteData(0xFF);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x0B);
    Ili9806WriteData(0x10);
    Ili9806WriteData(0x37);
    Ili9806WriteData(0x63);
    Ili9806WriteData(0xFF);
    Ili9806WriteData(0xFF);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0xFF);
    Ili9806WriteData(0x52);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x40);

    Ili9806WriteCmd(0xBD); // GIP 2
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x23);
    Ili9806WriteData(0x45);
    Ili9806WriteData(0x67);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0x23);
    Ili9806WriteData(0x45);
    Ili9806WriteData(0x67);

    Ili9806WriteCmd(0xBE); // GIP 3
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0xAB);
    Ili9806WriteData(0x60);
    Ili9806WriteData(0x22);
    Ili9806WriteData(0x22);
    Ili9806WriteData(0x22);
    Ili9806WriteData(0x22);
    Ili9806WriteData(0x22);

    Ili9806WriteCmd(0xC7); // VCOM Control
    Ili9806WriteData(g_c7param);

    Ili9806WriteCmd(0xED); // EN_volt_reg  VGMP / VGMN /VGSP / VGSN voltage to output
    Ili9806WriteData(0x7F);
    Ili9806WriteData(0x0F);

    Ili9806WriteCmd(0xC0); // Power Control 1 Setting AVDD / AVEE / VGH / VGL
    Ili9806WriteData(0x0F);
    Ili9806WriteData(0x0B);
    Ili9806WriteData(0x0A);//VGH 15V,VGLO-10V

    Ili9806WriteCmd(0xFC); //AVDD / AVEE generated by internal pumping.
    Ili9806WriteData(0x08);

    Ili9806WriteCmd(0xDF);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x20);

    Ili9806WriteCmd(0xF3);//DVDD Voltage Setting
    Ili9806WriteData(0x74);

    Ili9806WriteCmd(0xB4); // Inversion Type
    Ili9806WriteData(0x00);//02
    Ili9806WriteData(0x00);//02
    Ili9806WriteData(0x00);//02

    Ili9806WriteCmd(0xF7); // Resolution Control
    Ili9806WriteData(0x82);//480*800

    Ili9806WriteCmd(0xB1); // FRAME RATE Setting
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x13);
    Ili9806WriteData(0x13);

    Ili9806WriteCmd(0xF2); // CR_EQ_PC_SDT  #C0,06,40,28
    Ili9806WriteData(0x80);
    Ili9806WriteData(0x04);
    Ili9806WriteData(0x40);
    Ili9806WriteData(0x28);

    Ili9806WriteCmd(0xC1); // Power Control 2  SD OP Bias_VRH1_VRH2_EXT_CPCK_SEL
    Ili9806WriteData(0x17);
    Ili9806WriteData(0x88);//VGMP
    Ili9806WriteData(0x88);//VGMN
    Ili9806WriteData(0x20);

    Ili9806WriteCmd(0xE0);   //Positive Gamma Control
    Ili9806WriteData(0x00); //P1
    Ili9806WriteData(0x0A); //P2
    Ili9806WriteData(0x12); //P3
    Ili9806WriteData(0x10); //P4
    Ili9806WriteData(0x0E); //P5
    Ili9806WriteData(0x20); //P6
    Ili9806WriteData(0xCC); //P7
    Ili9806WriteData(0x07); //P8
    Ili9806WriteData(0x06); //P9
    Ili9806WriteData(0x0B); //P10
    Ili9806WriteData(0x0E); //P11
    Ili9806WriteData(0x0F); //P12
    Ili9806WriteData(0x0D); //P13
    Ili9806WriteData(0x15); //P14
    Ili9806WriteData(0x10); //P15
    Ili9806WriteData(0x00); //P16

    Ili9806WriteCmd(0xE1); //Negative Gamma Correction
    Ili9806WriteData(0x00); //P1
    Ili9806WriteData(0x0B); //P2
    Ili9806WriteData(0x13); //P3
    Ili9806WriteData(0x0D); //P4
    Ili9806WriteData(0x0E); //P5
    Ili9806WriteData(0x1B); //P6
    Ili9806WriteData(0x71); //P7
    Ili9806WriteData(0x06); //P8
    Ili9806WriteData(0x06); //P9
    Ili9806WriteData(0x0A); //P10
    Ili9806WriteData(0x0F); //P11
    Ili9806WriteData(0x0E); //P12
    Ili9806WriteData(0x0F); //P13
    Ili9806WriteData(0x15); //P14
    Ili9806WriteData(0x0C); //P15
    Ili9806WriteData(0x00); //P16

    Ili9806WriteCmd(0x2a);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x01);
    Ili9806WriteData(0xdf);

    Ili9806WriteCmd(0x2b);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x00);
    Ili9806WriteData(0x03);
    Ili9806WriteData(0x1f);

    Ili9806WriteCmd(0x3A); // Pixel Format
    Ili9806WriteData(0x55);

    Ili9806WriteCmd(0x36); //Memory Access Control
    Ili9806WriteData(0x00); //02-180

    Ili9806WriteCmd(0x11);
    UserDelay(120);
    Ili9806WriteCmd(0x29);
    UserDelay(20);
}
