on:
  pull_request:
    paths:
      - rust/apps/ergo/**

name: ERGO Checks

jobs:
  UnitTest:
    name: Unit Test And Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-01-31
          override: true
          components: rustfmt
          target: x86_64-apple-darwin

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run rust/apps/ergo
        run: cd rust/apps/ergo && cargo +nightly-2024-01-31 llvm-cov --fail-under-functions 50 --fail-under-lines 50 --fail-under-regions 50
