on:
  pull_request:
    paths:
      - rust/**

name: Rust checks

jobs:
  RustfmtCheck:
    name: Fmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Read Rust toolchain
        run: echo "RUST_TOOLCHAIN=$(cat rust-toolchain)" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          target: x86_64-apple-darwin
          components: rustfmt

      - name: Run rust/apps/bitcoin
        run: cd rust/apps/bitcoin && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/ethereum
        run: cd rust/apps/ethereum && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/solana
        run: cd rust/apps/solana && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/cardano
        run: cd rust/apps/cardano && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/tron
        run: cd rust/apps/tron && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/near
        run: cd rust/apps/near && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/xrp
        run: cd rust/apps/xrp && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/cosmos
        run: cd rust/apps/cosmos && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/aptos
        run: cd rust/apps/aptos && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/sui
        run: cd rust/apps/sui && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/arweave
        run: cd rust/apps/arweave && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/stellar
        run: cd rust/apps/stellar && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/utils
        run: cd rust/apps/utils && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/apps/wallets
        run: cd rust/apps/wallets && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/keystore
        run: cd rust/keystore && cargo +$RUST_TOOLCHAIN fmt --check
      - name: Run rust/rust_c
        run: cd rust/rust_c && cargo +$RUST_TOOLCHAIN fmt --check
