on:
  pull_request:
    paths:
      - rust/apps/wallets/**

name: Wallets Checks

jobs:
  UnitTest:
    name: Unit Test And Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-10-09
          override: true
          components: rustfmt
          target: x86_64-apple-darwin

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run rust/apps/wallets
        run: cd rust/apps/wallets && cargo +nightly-2024-10-09 llvm-cov --fail-under-regions 39 --fail-under-functions 40 --fail-under-lines 57
